version: '2.3'

services:
  backend:
    build:
      context: .
    depends_on:
      - cache
    volumes:
      - figmentator-data:/var/lib/figmentator/
    runtime: nvidia
    environment:
      - FIG_CACHE_URL=redis://cache
      - PYTHONPATH=/var/lib/figmentator/
      - FIG_FACTORY_INSTALL_DIR=/var/lib/figmentator/
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
  cache:
    image: redis:5-alpine
    volumes:
      - redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
volumes:
  figmentator-data:
