version: '2.3'

services:
  backend:
    build:
      args:
        - PIP_CMD=pip3 install -e
    ports:
      - ${PORT:-8882}:8800
    image: ${NAME:-figmentator}:dev
    volumes:
      - .:/var/www/figmentator/
    environment:
      - DEBUG=1
      - LOGLEVEL=debug
