#!/bin/sh

PORT="${PORT:-8800}"
HOST="${HOST:-0.0.0.0}"
WORKERS="${WORKERS:-1}"
LOGLEVEL="${LOGLEVEL:-info}"

if [ $DEBUG ]; then
  # Can't seem to get gunicorn to reload more than once, so fallback to using
  # uvicorn directly. This is fine since it's only during development. I
  # imagine it is a bug in gunicorn, but I don't feel like figuring that out at
  # the moment.
  uvicorn figmentator:app --reload --host $HOST --port $PORT --log-level $LOGLEVEL
else
  gunicorn -k uvicorn.workers.UvicornWorker -b "$HOST:$PORT" figmentator:app -w $WORKERS --log-level $LOGLEVEL
fi
